ktor:
  deployment:
    port: "$PORT:8080"
    tcpKeepAlive: true
    shareWorkGroup: false
    requestQueueLimit: 16
    responseWriteTimeoutSeconds: 10
  application:
    - ServerKt.module
database:
  driverName: "$DBDRIVER:org.postgresql.Driver"
  hostname: "$DBHOSTNAME://localhost"
  jdbcURL: "$JDBCURL:jdbc:postgresql"
  port: "$DBPORT:5432"
  username: "$DBCLIENTNAME:postgres"
  password: "$DBPASSWORD:postgres"
