ktor:
  deployment:
    port: "$PORT:8080"
    tcpKeepAlive: true
    shareWorkGroup: false
    requestQueueLimit: 16
    responseWriteTimeoutSeconds: 10
  application:
    - ServerKt.module
postgre:
  hostname: "$DBHOSTNAME:postgres"
  username: "$DBCLIENTNAME:postgres"
  password: "$DBPASSWORD:postgres"
