ktor:
  deployment:
    port: "$PORT:8080"
    sslPort: "$SSLPORT:8443"
    tcpKeepAlive: true
    shareWorkGroup: false
    requestQueueLimit: 16
    responseWriteTimeoutSeconds: 10
  application:
    modules:
      - ServerKt.module
  security:
    ssl:
      keyStore: "$SSLKEYSTOREPATH:keystore.jks"
      keyAlias: "$SSLKEYALIAS:testKeys"
      keyStorePassword: "$SSLKEYSTOREPASS:foobar"
      privateKeyPassword: "$SSLPKEYPASS:foobar"
database:
  init: "$DBINIT:true"
  driverName: "$DBDRIVER:org.postgresql.Driver"
  hostname: "$DBHOSTNAME://localhost"
  jdbcURL: "$JDBCURL:jdbc:postgresql"
  port: "$DBPORT:5432"
  username: "$DBCLIENTNAME:postgres"
  password: "$DBPASSWORD:postgres"
