ktor:
  deployment:
    port: "$PORT:80"
    sslPort: "$SSLPORT:8080"
    tcpKeepAlive: true
    shareWorkGroup: false
    requestQueueLimit: 16
    responseWriteTimeoutSeconds: 10
  application:
    modules:
      - ServerKt.module
  security:
    ssl:
      keyStore: "$SSLKEYSTOREPATH:keys/keystore.jks"
      keyAlias: "$SSLKEYALIAS:testKeys"
      keyStorePassword: "$SSLKEYSTOREPASS:foobar"
      privateKeyPassword: "$SSLPKEYPASS:foobar"
database:
  init: "$DBINIT:false"
  driverName: "$DBDRIVER:org.postgresql.Driver"
  hostname: "$DBHOSTNAME://localhost"
  jdbcURL: "$JDBCURL:jdbc:postgresql"
  port: "$DBPORT:5432"
  username: "$DBCLIENTNAME:postgres"
  password: "$DBPASSWORD:postgres"
jwt:
  secret: "$JWTSECRET:a5b486662c6b95de54054283fc81a51f493ab1967d857be86daff6a737738334"
  issuer: "$JWTISS:https://localhost"
  audience: "$JWTAUD:https://localhost/"
  realm: "$REALM:GeneralAuth"
github:
  clientid: "$GITCLIENTID:Ov23liJqi3HPj35vrItx"
  secret: "$GITSECRET:f2d2740953c74f90aef4f0599674b3f8ab690913"